Repository MangriMen/Paramoios, pull requests merged in 2020-05, with the labels that each got.

#11 Database creation
  default_data/alignment.json
  default_data/background.json
  default_data/class.json
  default_data/default_character.json
  default_data/race.json
  default_data/weapon.json
Labels: enhancement

#12 Character generate window
  .gitignore
  CharGenWindow.py
  CharGenWindow.ui
  MainWindow.py
  character_IO.py
  images/buttons/D6_0.png
  images/buttons/D6_1.png
  images/buttons/D6_2.png
  images/buttons/D6_3.png
  images/buttons/D6_4.png
  images/buttons/D6_5.png
  images/buttons/D6_6.png
  main.py
  saves/CharGenTemp/your_new_character.json
  style.py
Labels: enhancement

#14 Unittests
  .gitignore
  CharGenWindow.py
  MainWindow.py
  character_IO.py
  default_data/class.json
  default_data/json_schemes/alignmentSchema.json
  default_data/json_schemes/backgroundSchema.json
  default_data/json_schemes/characterSchema.json
  default_data/json_schemes/classSchema.json
  default_data/json_schemes/raceSchema.json
  default_data/test_character.json
  saves/CharGenTemp/.gitkeep
  test.py
Labels: unittest

#15 Travis ci
  .travis.yml
  CharGenWindow.py
  MainWindow.py
  character_IO.py
  make
  requirements.txt
Labels: unittest

#16 Develop
  .travis.yml
  CharGenWindow.py
  MainWindow.py
  MainWindow.ui
  character_IO.py
  default_data/default_character.json
  default_data/json_schemes/characterSchema.json
  default_data/race.json
  default_data/test_character.json
  images/buttons/D8_0.png
  images/buttons/D8_1.png
  images/buttons/D8_2.png
  images/buttons/D8_3.png
  images/buttons/D8_4.png
  images/buttons/D8_5.png
  images/buttons/D8_6.png
  images/buttons/D8_7.png
  images/buttons/D8_8.png
  style.py
  test.py
Labels: enhancement, unittest
