Repository MangriMen/Paramoios, pull requests merged in 2022-06, with the labels that each got.

#36 Bug/#30 Fix NavbarComponent unique key warning
  src/components/auth/LoginComponent.tsx
  src/components/auth/RegisterComponent.tsx
  src/components/common/NavbarComponent.tsx
  src/components/styled/ParAvatar.tsx
  src/components/styled/ParBox.tsx
  src/components/styled/ParLink.tsx
Labels: bug

#40 Bug/#36 Fix errors when login
  src/ducks/auth/index.ts
Labels: bug

#41 bug/#37 Fixed background color
  src/components/styled/ParBox.tsx
Labels: bug

#37 Feature/#26 Create error page
  src/assets/locales/ru/translation.json
  src/assets/styles/index.css
  src/components/AppContainer.tsx
  src/components/common/NotFoundPageComponent.tsx
Labels: feature

#39 Bug/#35 Fix confirm password filed in RegisterComponent
  src/components/auth/AuthFormField.tsx
  src/components/auth/LoginComponent.tsx
  src/components/auth/RegisterComponent.tsx
Labels: bug

#42 Feature/#24 Create user page
  .gitignore
  src/assets/locales/ru/translation.json
  src/components/AppContainer.tsx
  src/components/MainPageComponent.tsx
  src/components/auth/AuthPageComponent.tsx
  src/components/common/NavbarComponent.tsx
  src/components/styled/ParAvatar.tsx
  src/components/styled/ParLink.tsx
  src/components/user/UserCardComponent.tsx
  src/components/user/UserPageComponent.tsx
  src/consts/index.ts
  src/consts/paths.ts
  src/mocks/mockUserInfo.tsx
Labels: feature

#43 Feature/#51 Replaced console.log to console.error
  src/helpers/common.ts
Labels: feature

#47 Feature/#44 Removed unnecessary function component
  src/components/styled/ParContainer.tsx
Labels: feature

#51 Feature/#46 Added useCallback
  src/components/auth/AuthPageComponent.tsx
  src/components/auth/LoginComponent.tsx
  src/components/auth/RegisterComponent.tsx
Labels: feature

#48 Feature/#43 Removed children property, moved children inside tag
  src/components/styled/ParAvatar.tsx
Labels: feature

#50 Feature/#47 Replace functions on arrow functions
  src/components/App.tsx
  src/components/AppContainer.tsx
  src/components/MainPageComponent.tsx
  src/components/auth/AuthFormButton.tsx
  src/components/auth/AuthFormField.tsx
  src/components/auth/AuthPageComponent.tsx
  src/components/auth/LoginComponent.tsx
  src/components/auth/RegisterComponent.tsx
  src/components/common/NavbarComponent.tsx
  src/components/common/NotFoundPageComponent.tsx
  src/components/layout/PageWithNavbar.tsx
  src/components/styled/ParAvatar.tsx
  src/components/styled/ParBox.tsx
  src/components/styled/ParLink.tsx
  src/components/user/UserCardComponent.tsx
  src/components/user/UserPageComponent.tsx
Labels: feature

#49 Feature/#50 Remove from helpers what does not apply to helpers. Create jsdoc to helpers
  src/assets/fonts/EBERRON_RUS.otf
  src/assets/fonts/EBERRON_RUS.otf.back
  src/assets/images/icons/DA_Alert_White.svg
  src/assets/images/logo.svg
  src/assets/styles/index.css
  src/components/auth/AuthPageComponent.tsx
  src/components/auth/LoginComponent.tsx
  src/components/auth/RegisterComponent.tsx
  src/components/common/NavbarComponent.tsx
  src/components/user/UserCardComponent.tsx
  src/configs/firebase.ts
  src/configs/i18next.ts
  src/ducks/auth/services.ts
  src/ducks/store/index.ts
  src/helpers/avatar.ts
  src/helpers/common.ts
  src/index.tsx
  src/locales/ru/index.ts
  src/locales/ru/translation.json
  src/schemas/auth.ts
Labels: feature

#45 Feature/#41 Removed "component" from components name
  src/components/App.tsx
  src/components/AppContainer.tsx
  src/components/auth/FormButton.tsx
  src/components/auth/FormField.tsx
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/common/Navbar.tsx
  src/components/layout/PageWithNavbar.tsx
  src/components/pages/AuthPage.tsx
  src/components/pages/MainPage.tsx
  src/components/pages/NotFoundPage.tsx
  src/components/pages/UserPage.tsx
  src/components/user/UserCard.tsx
  src/index.tsx
  src/themes/default.ts
  src/themes/index.ts
Labels: feature

#52 Feature/#52 Implement theme change in auth/FormField
  src/components/auth/FormField.tsx
  src/components/auth/Login.tsx
Labels: feature

#54 Fix/#53 Fix register form input styles
  src/components/auth/Register.tsx
Labels: wontfix

#57 Feature/#40 Implement loader on auth page
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/auth/interfaces.ts
  src/components/common/Navbar.tsx
  src/components/pages/AuthPage.tsx
  src/ducks/auth/index.ts
  src/ducks/auth/selectors.ts
  src/ducks/user/index.ts
  src/ducks/user/selectors.ts
Labels: feature

#53 Feature/#10 Create roll dice button
  src/assets/images/dice/D10.svg
  src/assets/images/dice/D100.svg
  src/assets/images/dice/D12.svg
  src/assets/images/dice/D20.svg
  src/assets/images/dice/D4.svg
  src/assets/images/dice/D6.svg
  src/assets/images/dice/D8.svg
  src/components/App.tsx
  src/components/charlist/MainPage.tsx
  src/components/charlist/RollDiceButton.tsx
  src/components/charlist/interfaces.ts
Labels: feature

#58 Feature/#38 Create user settings
  src/components/App.tsx
  src/components/auth/FormButton.tsx
  src/components/auth/FormField.tsx
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/common/Navbar.tsx
  src/components/pages/AuthPage.tsx
  src/components/user/UserCard.tsx
  src/components/user/UserSettingsComponent.tsx
  src/components/user/interfaces.ts
  src/configs/firebase.ts
  src/ducks/auth/index.ts
  src/ducks/auth/sagas.ts
  src/ducks/auth/services.ts
  src/ducks/store/rootReducer.ts
  src/ducks/store/rootSaga.ts
  src/ducks/user/index.ts
  src/ducks/user/sagas.ts
  src/ducks/user/services.ts
  src/ducks/userSettings/index.ts
  src/ducks/userSettings/sagas.ts
  src/ducks/userSettings/services.ts
  src/locales/ru/translation.json
  src/mocks/mockUserInfo.tsx
  src/schemas/auth.ts
  src/schemas/userSettings.ts
  src/tools/requests/requests.ts
Labels: feature, wontfix
